In [20]:
import numpy as np
from scikit_roughsets.rs_reduction import RoughSetsReducer
reducer = RoughSetsReducer()
U = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 1],
              [1, 1],[1, 1], [1, 1], [1, 2], [2, 2], [2, 2]])
X = np.array([1,2,3,5])
B = np.array([1])
print(reducer.indisc(B,U))

[[ 1  2  3  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  6  7  8  0  0]
 [ 0  0  0  0  0  0  0  0  9 10]]


In [21]:
print(np.array(None))

print(len(reducer.rslower(X,B,U)))

AttributeError: 'list' object has no attribute 'astype'