In [14]:
import numpy as np
from scikit_roughsets.roughsets import RoughSetsReducer
reducer = RoughSetsReducer()
U = np.array([[0, 0],
              [0, 0],
              [0, 0],
              [0, 1],
              [1, 1],[1, 1], [1, 1], [1, 2], [2, 2], [2, 2]])
X = np.array([[1,2,3,5]])
B = np.array([1])
print(reducer.indisc(B,U))

[[ 1  2  3  4  0  0  0  0  0  0]
 [ 0  0  0  0  5  6  7  8  0  0]
 [ 0  0  0  0  0  0  0  0  9 10]]


In [19]:
print(np.array(None))

print(len(reducer.rslower(X,B,U)))
c =np.array([1,2,3])
def __size(x):
        return (1, x.shape[0]) if x.ndim == 1 else x.shape
print(__size(c))
cr,cc = __size(c)
for i in range(0,cc):
    print(i)

None
0
(1, 3)
0
1
2
